# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'inke' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for inke
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'YYKit'

end
